apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
apscheduler.scheduler - INFO - Added job "job" to job store "default"
apscheduler.scheduler - INFO - Scheduler started
root - INFO - Application started
apscheduler.executors.default - INFO - Running job "job (trigger: date[2024-05-16 09:22:11 CEST], next run at: 2024-05-16 09:22:11 CEST)" (scheduled at 2024-05-16 09:22:11.446362+02:00)
apscheduler.scheduler - INFO - Removed job 0800d128841443138c14f7a14d1bff76
root - INFO - Job started
werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://172.16.0.100:8000
werkzeug - INFO - [33mPress CTRL+C to quit[0m
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /check_possible/172.16.1.4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C25328D590>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /check_possible/172.16.2.4 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2533F1350>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /multi/False (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2533F3E50>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /multi/False (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253404B10>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /multinbr/False (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2533E89D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /multinbr/False (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253405110>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_demande_mode_multi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253421E90>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_demande_mode_multi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253422B10>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_alarme_urgence (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253426250>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_alarme_urgence (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2534278D0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_alarme_obstruation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253427550>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_alarme_obstruation (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253423DD0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_obstruation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253406290>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_obstruation (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253406650>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_urgence (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253433FD0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_urgence (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253433150>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': '0'}
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_sortie_normal (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253407350>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_sortie_normal (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253433B50>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': '0'}
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_sortie_secours (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253422F50>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_sortie_secours (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253420B10>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': '0'}
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_entree (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253427550>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_entree (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253440C90>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_surveillance_bille (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253420BD0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_surveillance_bille (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253422390>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C1_attention (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253407B90>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C1_attention (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253407A90>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C1_alerte (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253440610>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C2_attention (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253433E90>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C2_alerte (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253422190>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C3_attention (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253422810>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C3_alerte (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C25327BDD0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C4_attention (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253427E90>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C4_alerte (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253405F10>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_pause (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253404310>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_start (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253442ED0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'error': "'NoneType' object has no attribute 'read_area'"}
root - ERROR - {'error': "'NoneType' object has no attribute 'read_area'"}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_distribution (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253431410>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'error': "'NoneType' object has no attribute 'read_area'"}
root - ERROR - {'error': "'NoneType' object has no attribute 'read_area'"}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_sortie_secours (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2534218D0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'error': "'NoneType' object has no attribute 'read_area'"}
root - ERROR - {'error': "'NoneType' object has no attribute 'read_area'"}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_alarme_surveillance_bille (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253423690>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - unsupported operand type(s) for +: 'int' and 'dict'
root - ERROR - unsupported operand type(s) for +: 'int' and 'dict'
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /compteur_bille (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2533F2610>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /deconnection (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2533E8710>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - INFO - Job finished
apscheduler.scheduler - INFO - Added job "job" to job store "default"
apscheduler.executors.default - INFO - Job "job (trigger: date[2024-05-16 09:22:11 CEST], next run at: 2024-05-16 09:22:11 CEST)" executed successfully
apscheduler.executors.default - INFO - Running job "job (trigger: date[2024-05-16 09:31:39 CEST], next run at: 2024-05-16 09:31:39 CEST)" (scheduled at 2024-05-16 09:31:39.669479+02:00)
apscheduler.scheduler - INFO - Removed job 25c1fdc5724a4b049ac65a22b15fe2b9
root - INFO - Job started
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /check_possible/172.16.2.4 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2533BEED0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /multi/True (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2533F18D0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /multinbr/False (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2533E85D0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_demande_mode_multi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253426610>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_alarme_urgence (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253433210>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_alarme_obstruation (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253420BD0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_obstruation (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253442E50>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_urgence (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253440E50>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - INFO - {'message': '74'}
root - INFO - {'message': '74'}
root - INFO - {'message': 'Sortie set for Mw_master_nb_billes_sortie_normal'}
root - INFO - {'message': 'Sortie set for Mw_master_nb_billes_sortie_normal'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_sortie_normal (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253431310>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /sortie/Mw_master_nb_billes_sortie_normal/True (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2534300D0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /sortie/Mw_master_nb_billes_sortie_normal/True (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253433D50>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - INFO - {'message': 'Sortie set for Mw_master_nb_billes_sortie_normal'}
root - INFO - {'message': 'Sortie set for Mw_master_nb_billes_sortie_normal'}
root - ERROR - {'message': '0'}
root - ERROR - {'message': '0'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_sortie_secours (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2534242D0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - INFO - {'message': '52'}
root - INFO - {'message': '52'}
root - INFO - {'message': 'Sortie set for Mw_master_nb_billes_entree'}
root - INFO - {'message': 'Sortie set for Mw_master_nb_billes_entree'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_entree (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253422E90>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /sortie/Mw_master_nb_billes_entree/True (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253430410>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /sortie/Mw_master_nb_billes_entree/True (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253425AD0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - INFO - {'message': 'Sortie set for Mw_master_nb_billes_entree'}
root - INFO - {'message': 'Sortie set for Mw_master_nb_billes_entree'}
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_surveillance_bille (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253406D90>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C1_attention (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253406610>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C1_alerte (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253443F10>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C2_attention (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253442650>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - {'message': 'False'}
root - ERROR - {'message': 'False'}
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C2_alerte (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2534202D0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C3_attention (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253433910>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C3_attention (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253440590>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C3_attention (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253404510>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C3_alerte (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253423610>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C3_alerte (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253420250>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C3_alerte (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2528F4250>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C4_attention (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253404210>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C4_attention (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253443F10>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C4_attention (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2534418D0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C4_alerte (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2525F1B10>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C4_alerte (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2534054D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C4_alerte (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253405690>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_pause (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253431F10>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_pause (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253441F10>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_pause (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253431610>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_start (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253431F10>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_start (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253431D90>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_start (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253421B50>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_distribution (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253425610>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_distribution (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253443710>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_distribution (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253324750>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_sortie_secours (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253425610>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_sortie_secours (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253425210>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_sortie_secours (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2533BE7D0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_alarme_surveillance_bille (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253430B10>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_alarme_surveillance_bille (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253441E50>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_alarme_surveillance_bille (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253433C90>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /compteur_bille (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2533F36D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /compteur_bille (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253294650>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /compteur_bille (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253406E50>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /deconnection (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2533F2850>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /deconnection (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C25328E690>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /deconnection (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2533F1E50>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - INFO - Job finished
apscheduler.scheduler - INFO - Added job "job" to job store "default"
apscheduler.scheduler - INFO - Removed job 6da5a39395da418aadbd30ea0e2bab50
apscheduler.executors.default - INFO - Running job "job (trigger: date[2024-05-16 09:41:08 CEST], next run at: 2024-05-16 09:41:08 CEST)" (scheduled at 2024-05-16 09:41:08.216250+02:00)
apscheduler.executors.default - INFO - Job "job (trigger: date[2024-05-16 09:31:39 CEST], next run at: 2024-05-16 09:31:39 CEST)" executed successfully
root - INFO - Job started
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /check_possible/172.16.3.4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2533BE350>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /check_possible/172.16.1.4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253425F90>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /check_possible/172.16.2.4 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253426B10>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /multi/False (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2533F1ED0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /multi/False (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2533F2AD0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /multi/False (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C25324ED10>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /multinbr/False (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253424A50>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /multinbr/False (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C25335B790>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /multinbr/False (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2533BCE10>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_demande_mode_multi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253442210>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_demande_mode_multi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253441950>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_demande_mode_multi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253432E90>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_alarme_urgence (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2533E8A10>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_alarme_urgence (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2533EA6D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_alarme_urgence (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2532A96D0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_alarme_obstruation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C25343C410>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_alarme_obstruation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2532AB810>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_alarme_obstruation (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253421B10>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_obstruation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253432D90>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_obstruation (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2533BFBD0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_obstruation (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253433B90>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_urgence (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2533BF110>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_urgence (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C25343FAD0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_urgence (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253444610>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_sortie_normal (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253423750>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_sortie_normal (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253421ED0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_sortie_normal (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253420290>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_sortie_secours (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2532A9990>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_sortie_secours (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C25327AFD0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_sortie_secours (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253423550>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_entree (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253430490>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_entree (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253441090>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mw_master_nb_billes_entree (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253431490>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_surveillance_bille (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2532AA950>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_surveillance_bille (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253431490>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_master_quittance_surveillance_bille (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2534318D0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C1_attention (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2533E8C90>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C1_attention (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C25343F310>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C1_attention (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2533E8C50>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C1_alerte (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253422C90>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C1_alerte (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2533E9750>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C1_alerte (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2534235D0>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C2_attention (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C25343E2D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C2_attention (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253407390>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C2_attention (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253442510>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C2_alerte (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2534267D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C2_alerte (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2534328D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C2_alerte (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2532AB450>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C3_attention (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2533E9510>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C3_attention (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C25343D9D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C3_attention (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253440C90>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C3_alerte (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2533EB7D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C3_alerte (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C253420890>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C3_alerte (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C253442B50>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C4_attention (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C25343F950>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C4_attention (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C25343C210>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.0.105', port=8000): Max retries exceeded with url: /trigger/Mx_API_C4_attention (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C2532A9150>, 'Connection to 172.16.0.105 timed out. (connect timeout=None)'))
root - ERROR - HTTPConnectionPool(host='172.16.1.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C4_alerte (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2533BEB90>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
root - ERROR - HTTPConnectionPool(host='172.16.3.2', port=8000): Max retries exceeded with url: /trigger/Mx_API_C4_alerte (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C2532A9910>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
